# Visit https://github.com/lowlighter/metrics#-documentation for full reference
# Visit https://metrics.lecoq.io/embed?user= to generate action code
# Visit https://github.com/lowlighter/metrics/blob/latest/README.md#-plugins for plugin index

# Set up GitHub Actions:
# https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
# Update token here: https://github.com/settings/tokens/new
# scope: (scopeless)

name: Metrics
on:
  # Schedule updates (every day)
  schedule: [{cron: "0 6,18 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: alexhyang
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: US/Pacific
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 5%
          plugin_languages: yes
          plugin_languages_aliases: JSX:JavaScript TSX:TypeScript
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 28
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 5%
          plugin_wakatime: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages, editors, os, languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
